# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stamps Studio
#email: infostampscr@gmail.com
email: guayo.mena@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  El diseño, la creatividad y la creación de conceptos son nuestra pasión. Nos encanta tener nuevos retos y nuevos proyectos para trabajar, esperamos poder ayudarle a crear una mejor imagen para su marca.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
telefono: +506 6070-0083

# Build settings
markdown: kramdown

description-extended: "<i>La inspiración existe, pero tiene que encontrarte trabajando</i> – Pablo Picasso"
